### ISSUE TITLE
Multiple wavelets with one parameter file? [FEAT EXTRACTION]

### ISSUE THREAD

**Issue by asy51** [AIM-Harvard/pyradiomics#723]
Is it possible to configure a parameter file to make it generate a set of features for each wavelet decomposition type?
```
imageType:
  Wavelet1:
    wavelet: 'haar'
    start_level: 0
    level: 1
  Wavelet2:
    wavelet: 'coif1'
    start_level: 1
    level: 2
```

PS: Also want to confirm that the empty dict `Wavelet: {}` signifies default values, equivalent to:
```
imageType:
  Wavelet:
    wavelet: 'coif1'
    start_level: 0
    level: 1
```

**Comment by helderc** [comment]
Hello, I'm looking for something similar.

I want to specify more than one Wavelet. According to the documentation, this should work:
```Python
extractor.enableImageTypeByName('Wavelet', customArgs={'wavelet':['db4', 'dmey'], 'level':[4]})
```

But I got the error: `AttributeError: 'list' object has no attribute 'lower'`

I even try to use a `Params.yaml` file but the error is the same:
```Yaml
imageType:
  Wavelet: 
    wavelet: ['db4', 'dmey']
    level: 4
```

Is there any way to do this?
