### ISSUE TITLE
[BUG] Segmentation fault (core dumped) in voxel-wise feature extraction

### ISSUE THREAD

**Issue by mligerhe** [AIM-Harvard/pyradiomics#737]
**Describe the bug**
When I try to run a voxel-wise feature extraction, I get the following error: 'Segmentation fault (core dumped)'. The 

`
extractor = featureextractor.RadiomicsFeatureExtractor(**params)extractor.disableAllFeatures()
extractor.enableFeatureClassByName('glcm')
voxel_result = extractor.execute(image1, mask, label = labels[0], voxelBased=True)
`

**PyRadiomics configuration**
Add any customization you applied here (i.e. the content of the parameter file used)

**PyRadiomics log file**
If available, add section of the PyRadiomics log showing your error. For help on setting up logging, see the [online documentation](https://pyradiomics.readthedocs.io/en/latest/usage.html#setting-up-logging)

**To Reproduce**

**Expected behavior**

**Version (please complete the following information):**
 - Python version: [e.g. 3.6]
 - PyRadiomics version [e.g. 2.2.0]

**Additional context**

**Comment by JoostJM** [comment]
Can you share a sample of the image/mask for debugging?

**Comment by mligerhe** [comment]
[pyradiomics_testimages.zip](https://github.com/AIM-Harvard/pyradiomics/files/7711478/pyradiomics_testimages.zip)


> Can you share a sample of the image/mask for debugging?
[pyradiomics_testimages.zip](https://github.com/AIM-Harvard/pyradiomics/files/7711897/pyradiomics_testimages.zip)

**Comment by md863** [comment]
Hi, I'm encountering this same issue. Is there any update?
Thanks!

**Comment by llu025** [comment]
Same here with any first order feature extraction. It works like a charm with any other features (`glcm`, `glrlm`, etc.).

### PyRadiomics configuration
```
imageType:
  Original: {}

featureClass:
  firstorder:
    - 'Minimum'

setting:
  normalize: true
  normalizeScale: 100
  binWidth: 25
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [1, 1, 1]
  correctMask: true
  voxelArrayShift: 300
  force2D: true
  force2Ddimension: 0

voxelSetting:
  kernelRadius: 1
  maskedKernel: true
  voxelBatch: 10000
```

### To reproduce

```
extractor = featureextractor.RadiomicsFeatureExtractor(PRM_PATH)
features = extractor.execute(IMG, SEG, voxelBased=True)
```

### Output
```
[1]    61328 segmentation fault  python3 main.py
```

### Expected behavior
Working just fine

### Version

- OS: MacOS Monterey 12.3.1 (M1 chip)
- Python version: 3.9.12
- PyRadiomics version 3.0.1

**Comment by llu025** [comment]
⬆️ ⬆️ ⬆️

**Comment by ginagigo123** [comment]
Hi, I'm encountering this same issue. Is there any update?
Thanks!

**Comment by francescopisu** [comment]
```
setting:
  binWidth: 25  # Changed from 10  to 25 solved the issue
  label: 1
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: 
  weightingNorm:
  force2D: False
  symmetricalGLCM: True


imageType:
  Original: {}

featureClass:
  glcm:
    - 'Correlation'
  gldm:
    - SmallDependenceLowGrayLevelEmphasis
  ngtdm:
    - Coarseness
```

Using the above settings with binWidth: 10 I got this error:
```
Loading parameter file ./pyradiomics.yaml
Parameters parsed, input is valid.
Applying settings
Enabled image types: {'Original': {}}
Enabled features: {'glcm': ['Correlation'], 'gldm': ['SmallDependenceLowGrayLevelEmphasis'], 'ngtdm': ['Coarseness']}
Settings: {'binWidth': 10, 'label': 1, 'interpolator': 'sitkBSpline', 'weightingNorm': None, 'force2D': False, 'resampledPixelSpacing': None, 'symmetricalGLCM': True}
Starting voxel based extraction
Calculating features with label: 1
Enabled images types: {'Original': {}}
Enabled features: {'glcm': ['Correlation'], 'gldm': ['SmallDependenceLowGrayLevelEmphasis'], 'ngtdm': ['Coarseness']}
Current settings: {'minimumROIDimensions': 2, 'minimumROISize': None, 'normalize': False, 'normalizeScale': 1, 'removeOutliers': None, 'resampledPixelSpacing': None, 'interpolator': 'sitkBSpline', 'preCrop': False, 'padDistance': 5, 'distances': [1], 'force2D': False, 'force2Ddimension': 0, 'resegmentRange': None, 'label': 1, 'additionalInfo': True, 'binWidth': 10, 'weightingNorm': None, 'symmetricalGLCM': True, 'voxelBased': True}
Loading image and mask
Force casting mask to UInt32 to ensure correct datatype.
Checking mask with label 1
Calculating bounding box
Checking minimum number of dimensions requirements (2)
Image and Mask loaded and valid, starting extraction
Creating image type iterator
Adding image type "Original" with custom settings: {}
Extracting features
Yielding original image
Calculating features for original image
Cropping to size [62 60 82]
Computing glcm
Initializing feature class
Discretizing gray levels inside ROI
Calculated 133 bins for bin width 10 with edges: [-150 -140 -130 -120 -110 -100  -90  -80  -70  -60  -50  -40  -30  -20
  -10    0   10   20   30   40   50   60   70   80   90  100  110  120
  130  140  150  160  170  180  190  200  210  220  230  240  250  260
  270  280  290  300  310  320  330  340  350  360  370  380  390  400
  410  420  430  440  450  460  470  480  490  500  510  520  530  540
  550  560  570  580  590  600  610  620  630  640  650  660  670  680
  690  700  710  720  730  740  750  760  770  780  790  800  810  820
  830  840  850  860  870  880  890  900  910  920  930  940  950  960
  970  980  990 1000 1010 1020 1030 1040 1050 1060 1070 1080 1090 1100
 1110 1120 1130 1140 1150 1160 1170 1180])
Calculating voxel batch no. 1/1
Calculating GLCM matrix in C
Segmentation fault (core dumped)
```

Changing to 25 (arbitrarily chosen) solved the issue.
