### ISSUE TITLE
First Order feature maps

### ISSUE THREAD

**Issue by MicheleMureddu** [AIM-Harvard/pyradiomics#862]
Hi
i was trying to extract first order feature maps with this configurations:

```
setting:
  binWidth: 0.3125
  label: 1
  interpolator: 'sitkBSpline'
  resampledPixelSpacing:   
  resegmentMode: 'absolute'
  resegmentRange: [0,20]


imageType:
  Original: {} 

```
For all the textural features the code seems to work and i obtain feature maps. If i enable, for example, first order entropy i get "segmentation fault (core dumped).
