### ISSUE TITLE
[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by dsantiago** [AIM-Harvard/pyradiomics#869]
I am using the following configuration file in radiomics v3.0.1, but found out that it's probably because it's in old format.

I want, like described in the file, the **percentiles** 10, 25, and 50. Checking the documentation and the new format, I found that I must set in the file internal functions and for percentiles there's only: `get10PercentileFeatureValue()` and `get90PercentileFeatureValue()`

Is there any way to use percentiles 10, 25, and 50?

```yaml
---
enabledFeatures:
  - firstorder
  - glcm
  - shape
  - texture
  - intensity
  - morphology

imageType:
  - ORIGINAL

settings:
  binWidth:  25
  resampledPixelSpacing: [1,1,1]
  interpolation: Linear
  enableCExtensions: True
  smooth:
    - LaplacianOfGaussian
  smooth_params:
    - sigma: [1.0,  2.0,  3.0,  4.0,  5.0]
  intensity_features:
    - mean
    - standard_deviation
    - percentiles: [10,  25,  50]
    - percentiles_SD: [10,  25,  50]
    - kurtosis
    - skewness
  glcm_features:
    - contrast
    - entropy
    - homogeneity
    - energy
    - correlation
    - uniformity
    - dissimilarity
  glcm_directions: [0,  45,  90,  135]
  glcm_distances: [1,  2,  3]
```
